// source: sensehat.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.SensorData', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SensorData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.SensorData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.SensorData.displayName = 'proto.SensorData';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SensorData.prototype.toObject = function(opt_includeInstance) {
  return proto.SensorData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SensorData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SensorData.toObject = function(includeInstance, msg) {
  var f, obj = {
    temperature: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
    humidity: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
    pressure: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
    magnetometerx: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
    magnetometery: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
    magnetometerz: jspb.Message.getFloatingPointFieldWithDefault(msg, 6, 0.0),
    acceldegroll: jspb.Message.getFloatingPointFieldWithDefault(msg, 7, 0.0),
    acceldegpitch: jspb.Message.getFloatingPointFieldWithDefault(msg, 8, 0.0),
    acceldegyaw: jspb.Message.getFloatingPointFieldWithDefault(msg, 9, 0.0),
    gyrodegroll: jspb.Message.getFloatingPointFieldWithDefault(msg, 10, 0.0),
    gyrodegpitch: jspb.Message.getFloatingPointFieldWithDefault(msg, 11, 0.0),
    gyrodegyaw: jspb.Message.getFloatingPointFieldWithDefault(msg, 12, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SensorData}
 */
proto.SensorData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SensorData;
  return proto.SensorData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SensorData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SensorData}
 */
proto.SensorData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setTemperature(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setHumidity(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setPressure(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setMagnetometerx(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setMagnetometery(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setMagnetometerz(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setAcceldegroll(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setAcceldegpitch(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setAcceldegyaw(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setGyrodegroll(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setGyrodegpitch(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setGyrodegyaw(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SensorData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SensorData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SensorData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SensorData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTemperature();
  if (f !== 0.0) {
    writer.writeFloat(
      1,
      f
    );
  }
  f = message.getHumidity();
  if (f !== 0.0) {
    writer.writeFloat(
      2,
      f
    );
  }
  f = message.getPressure();
  if (f !== 0.0) {
    writer.writeFloat(
      3,
      f
    );
  }
  f = message.getMagnetometerx();
  if (f !== 0.0) {
    writer.writeFloat(
      4,
      f
    );
  }
  f = message.getMagnetometery();
  if (f !== 0.0) {
    writer.writeFloat(
      5,
      f
    );
  }
  f = message.getMagnetometerz();
  if (f !== 0.0) {
    writer.writeFloat(
      6,
      f
    );
  }
  f = message.getAcceldegroll();
  if (f !== 0.0) {
    writer.writeFloat(
      7,
      f
    );
  }
  f = message.getAcceldegpitch();
  if (f !== 0.0) {
    writer.writeFloat(
      8,
      f
    );
  }
  f = message.getAcceldegyaw();
  if (f !== 0.0) {
    writer.writeFloat(
      9,
      f
    );
  }
  f = message.getGyrodegroll();
  if (f !== 0.0) {
    writer.writeFloat(
      10,
      f
    );
  }
  f = message.getGyrodegpitch();
  if (f !== 0.0) {
    writer.writeFloat(
      11,
      f
    );
  }
  f = message.getGyrodegyaw();
  if (f !== 0.0) {
    writer.writeFloat(
      12,
      f
    );
  }
};


/**
 * optional float temperature = 1;
 * @return {number}
 */
proto.SensorData.prototype.getTemperature = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.SensorData} returns this
 */
proto.SensorData.prototype.setTemperature = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional float humidity = 2;
 * @return {number}
 */
proto.SensorData.prototype.getHumidity = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.SensorData} returns this
 */
proto.SensorData.prototype.setHumidity = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional float pressure = 3;
 * @return {number}
 */
proto.SensorData.prototype.getPressure = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.SensorData} returns this
 */
proto.SensorData.prototype.setPressure = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional float magnetometerX = 4;
 * @return {number}
 */
proto.SensorData.prototype.getMagnetometerx = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.SensorData} returns this
 */
proto.SensorData.prototype.setMagnetometerx = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional float magnetometerY = 5;
 * @return {number}
 */
proto.SensorData.prototype.getMagnetometery = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.SensorData} returns this
 */
proto.SensorData.prototype.setMagnetometery = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * optional float magnetometerZ = 6;
 * @return {number}
 */
proto.SensorData.prototype.getMagnetometerz = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.SensorData} returns this
 */
proto.SensorData.prototype.setMagnetometerz = function(value) {
  return jspb.Message.setProto3FloatField(this, 6, value);
};


/**
 * optional float accelDegRoll = 7;
 * @return {number}
 */
proto.SensorData.prototype.getAcceldegroll = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 7, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.SensorData} returns this
 */
proto.SensorData.prototype.setAcceldegroll = function(value) {
  return jspb.Message.setProto3FloatField(this, 7, value);
};


/**
 * optional float accelDegPitch = 8;
 * @return {number}
 */
proto.SensorData.prototype.getAcceldegpitch = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 8, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.SensorData} returns this
 */
proto.SensorData.prototype.setAcceldegpitch = function(value) {
  return jspb.Message.setProto3FloatField(this, 8, value);
};


/**
 * optional float accelDegYaw = 9;
 * @return {number}
 */
proto.SensorData.prototype.getAcceldegyaw = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 9, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.SensorData} returns this
 */
proto.SensorData.prototype.setAcceldegyaw = function(value) {
  return jspb.Message.setProto3FloatField(this, 9, value);
};


/**
 * optional float gyroDegRoll = 10;
 * @return {number}
 */
proto.SensorData.prototype.getGyrodegroll = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 10, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.SensorData} returns this
 */
proto.SensorData.prototype.setGyrodegroll = function(value) {
  return jspb.Message.setProto3FloatField(this, 10, value);
};


/**
 * optional float gyroDegPitch = 11;
 * @return {number}
 */
proto.SensorData.prototype.getGyrodegpitch = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 11, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.SensorData} returns this
 */
proto.SensorData.prototype.setGyrodegpitch = function(value) {
  return jspb.Message.setProto3FloatField(this, 11, value);
};


/**
 * optional float gyroDegYaw = 12;
 * @return {number}
 */
proto.SensorData.prototype.getGyrodegyaw = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 12, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.SensorData} returns this
 */
proto.SensorData.prototype.setGyrodegyaw = function(value) {
  return jspb.Message.setProto3FloatField(this, 12, value);
};


goog.object.extend(exports, proto);
